export const darkColors = {
  bg:            '#07000F',
  bgDeep:        '#0C0018',
  bgDanger:      '#0E000E',
  card:          '#120028',
  cardElevated:  '#1A003A',
  border:        '#3A1A6A',
  borderFaint:   '#27104A',
  borderFocus:   '#B478F0',
  borderDanger:  '#3A0A2A',
  accent:        '#B478F0',
  accentBtn:     '#7B2FBE',
  textPrimary:   '#FFFFFF',
  textSecondary: '#CCAAFF',
  textMuted:     '#4A2070',
  textFaint:     '#27104A',
  textDanger:    '#F87171',
  textGreen:     '#4ADE80',
  placeholder:   '#4A2070',
  starColor:     '#FFFFFF',
  statusBar:     'light',
};

export const lightColors = {
  bg:            '#F4EEFF',
  bgDeep:        '#EAE0FF',
  bgDanger:      '#FEF2F2',
  card:          '#FFFFFF',
  cardElevated:  '#EEE6FF',
  border:        '#C9B8E8',
  borderFaint:   '#E2D5F5',
  borderFocus:   '#7B2FBE',
  borderDanger:  '#FECACA',
  accent:        '#7B2FBE',
  accentBtn:     '#7B2FBE',
  textPrimary:   '#0D0020',
  textSecondary: '#5B3A8A',
  textMuted:     '#8B6AAA',
  textFaint:     '#C4B0E0',
  textDanger:    '#DC2626',
  textGreen:     '#15803D',
  placeholder:   '#A898C8',
  starColor:     '#3A1A6A',
  statusBar:     'dark',
};
